name: 'Publish metadata and artifacts with hc-releases'
description: 'Use hc-releases to create metadata and upload files.'
inputs:
  product-name:
    description: 'Product name'
    required: true
  version:
    description: 'Product version'
    required: true
  source-env:
    description: 'Source env'
    required: false
    default: "staging"
  hc-releases-host:
    description: 'hc releases host'
    required: true
  hc-releases-key:
    description: 'hc releases api key'
    required: true
  hc-releases-source_env_key:
    description: 'hc releases source env api key'
    required: true
runs:
  using: "composite"
  steps:
      - name: Promote artifacts and release meta-data
        shell: bash
        env:
          HC_RELEASES_HOST: ${{ inputs.hc-releases-host }}
          HC_RELEASES_KEY: ${{ inputs.hc-releases-key }}
          HC_RELEASES_SOURCE_ENV_KEY: ${{ inputs.hc-releases-source_env_key }}
          VERSION: ${{ inputs.version }}
          PRODUCT_NAME: ${{ inputs.product-name }}
          SOURCE_ENV: ${{ inputs.source-env }}
        run: |
          ${{ github.action_path }}/scripts/promote.sh
