name: test
on: [push]

jobs:
  action-test-skip-set:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Invoke Action
        uses: ./ # This is the action we're testing.
        with:
          hc-releases-host: api.releases.hashicorp.com
          hc-releases-key: some-key
          hc-releases-source_env_key: some-source-env-key
          version: test
          product-name: terraform-provider-archive
          source-env: staging
          skip-terraform-registry-sync: "true"
  action-test-skip-not-set:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Invoke Action
        uses: ./ # This is the action we're testing.
        with:
          hc-releases-host: api.releases.hashicorp.com
          hc-releases-key: some-key
          hc-releases-source_env_key: some-source-env-key
          version: test
          product-name: terraform-provider-archive
          source-env: staging
          hc-releases-terraform-registry-sync-token: sometoken
